import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import navbar from '@/styles/Navbar.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Prabhjot Sodhi's Next JS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <header className={navbar.nav_container}>
        <section className="container">
          <div className={navbar.nav_wrapper}>
            <a href="/" className={navbar.logo_text}><h2>Prabhjot Sodhi</h2></a>
            <button className={navbar.mobile_nav_toggle} aria-controls="primary-navigation" aria-expanded="false">
              <img className={navbar.icon_hamburger} src="/hamburger.svg" alt=""></img>
              <img className={navbar.icon_close} src="/hamburger-close.svg"></img>
            </button>
            <nav className={navbar.primary_navigation} id="primary-navigation">
                <ul className={navbar.nav_list}>
                    <li><a href="/projects" data-id="projects">projects</a></li>
                    <li><a href="/writing" data-id="writing">writing</a></li>
                </ul>
            </nav>
          </div>
        </section>
      </header>

      <main>
        <section className="padding-section" style={{borderBottom: "3px solid var(--clr-neutral-900);"}}>
          <div className="container">
            <h2>👋 Hi, I&apos;m Prabhjot! </h2>
            <h1>Unleashing creativity through <span>words</span> and bringing ideas to life through <span>code</span>.</h1>
          </div>
        </section>
      </main>
    </>
  )
}
